# Generated by Django 2.0.1 on 2018-03-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='host_groups',
            field=models.ManyToManyField(blank=True, to='audit.HostGroup'),
        ),
        migrations.AlterField(
            model_name='account',
            name='host_user_bind',
            field=models.ManyToManyField(blank=True, to='audit.HostUserBind'),
        ),
    ]
