# Generated by Django 2.0.1 on 2018-04-04 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20180404_1529'),
    ]

    operations = [
    ]
