# Generated by Django 2.0.1 on 2018-04-04 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auto_20180404_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionlog',
            name='account',
        ),
        migrations.RemoveField(
            model_name='sessionlog',
            name='host_user_bind',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='cmd',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='session',
        ),
        migrations.DeleteModel(
            name='SessionLog',
        ),
    ]
