# Generated by Django 2.0.1 on 2018-04-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_auto_20180405_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='cmd',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
