# Generated by Django 2.0.4 on 2018-04-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_auto_20180411_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='val',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set(),
        ),
    ]
