# Generated by Django 2.0.1 on 2018-04-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0009_auto_20180417_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskout',
            field=models.IntegerField(default=300, verbose_name='任务超时'),
        ),
    ]
