# Generated by Django 2.0.1 on 2018-04-17 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0010_task_taskout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='host_user_binds',
        ),
    ]
