# Generated by Django 2.0.1 on 2018-04-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0011_remove_task_host_user_binds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='result',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='status',
            field=models.IntegerField(choices=[(0, '成功'), (1, '失败'), (2, '超时'), (3, '初始化')]),
        ),
    ]
