# Generated by Django 2.0.1 on 2018-04-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0012_auto_20180417_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='result',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
