# Generated by Django 2.0.1 on 2018-04-18 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0014_auto_20180417_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='taskout',
            new_name='timeout',
        ),
    ]
